name: Release macOS Build (Public)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  release-macos:
    runs-on: macos-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
      - name: Clone private repository
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git clone https://thacio:${GITHUB_TOKEN}@github.com/thacio/md_to_docx_parser.git private-repo
          cd private-repo
          echo "Successfully cloned private repository"
          git log -1 --oneline

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka ordered-set zstandard
          pip install -r private-repo/tcu-writing/requirements.txt

      - name: Generate embedded templates
        run: |
          cd private-repo/tcu-writing
          echo "Generating embedded python-docx templates..."
          python generate_embedded_templates.py
          ls -lh embedded_templates.py

      - name: Compile with Nuitka (onefile mode)
        run: |
          cd private-repo/tcu-writing
          echo "Compiling TRUE ONEFILE executable..."

          python -m nuitka \
            --onefile \
            --enable-plugin=anti-bloat \
            --assume-yes-for-downloads \
            --include-package-data=latex2mathml \
            --output-filename=tcu-parser \
            parser.py

          echo "Compilation complete!"
          ls -lh tcu-parser
          file tcu-parser

      - name: Create distribution package
        run: |
          cd private-repo/tcu-writing

          # Create a clean distribution directory
          mkdir -p ../../tcu-parser-macos

          # Copy executable
          cp tcu-parser ../../tcu-parser-macos/
          chmod +x ../../tcu-parser-macos/tcu-parser

          # Copy documentation and templates
          cp -r assets ../../tcu-parser-macos/
          cp -r templates ../../tcu-parser-macos/
          cp syntax_guide.md ../../tcu-parser-macos/ 2>/dev/null || true
          cp syntax_cheatsheet.md ../../tcu-parser-macos/ 2>/dev/null || true
          cp tcu_writing_guide.md ../../tcu-parser-macos/ 2>/dev/null || true
          cp SKILL.md ../../tcu-parser-macos/ 2>/dev/null || true
          cp README.md ../../tcu-parser-macos/ 2>/dev/null || true

          # Create README
          cat > ../../tcu-parser-macos/README.txt << 'EOF'
          TCU Parser - macOS Distribution
          ================================

          True single-file executable with embedded templates.
          No extraction to /tmp/ - fully self-contained!

          Usage:
            ./tcu-parser input.md [-o output.docx]

          Examples:
            ./tcu-parser templates/instrucao_padrao.md
            ./tcu-parser my-document.md -o my-output.docx

          Documentation:
            - syntax_guide.md (complete reference)
            - syntax_cheatsheet.md (quick reference)
            - tcu_writing_guide.md (TCU compliance guide)

          Platform: macOS (Universal binary - Intel and Apple Silicon)
          Build: Nuitka onefile with embedded python-docx templates
          EOF

          # Create ZIP archive
          cd ../..
          zip -r tcu-parser-macos.zip tcu-parser-macos/

          echo "Package created:"
          ls -lh tcu-parser-macos.zip

      - name: Get version info from private repo
        id: version
        run: |
          cd private-repo
          SHORT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B | head -1)
          BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "commit_msg=${COMMIT_MSG}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-macos
          name: "Latest macOS Build"
          body: |
            ## TCU Parser - macOS Build

            **Platform:** macOS (Universal - Intel & Apple Silicon)
            **Build Type:** True onefile with embedded templates
            **Build Date:** ${{ steps.version.outputs.build_date }}
            **Source Commit:** ${{ steps.version.outputs.short_sha }}
            **Message:** ${{ steps.version.outputs.commit_msg }}

            ### Download

            Download `tcu-parser-macos.zip` below and extract it.

            ### Fixed URL Access

            You can always get the latest macOS build from:
            ```
            https://github.com/thacio/markup_to_docx_parser_release/releases/download/latest-macos/tcu-parser-macos.zip
            ```

            ### Quick Start

            ```bash
            # Extract the archive
            unzip tcu-parser-macos.zip
            cd tcu-parser-macos

            # Make executable (if needed)
            chmod +x tcu-parser

            # Test it
            ./tcu-parser templates/instrucao_padrao.md
            ```

            ### What's Included

            - ✅ Single executable file (~21-25MB)
            - ✅ Embedded python-docx templates (no /tmp/ extraction)
            - ✅ Example templates (instrucao_padrao, plano_auditoria, analise_separada)
            - ✅ Complete documentation (syntax guides, TCU compliance)
            - ✅ Assets (TCU logo, etc.)

            ### Source

            This build is generated from the private repository.
            Source commit: ${{ steps.version.outputs.short_sha }}
          files: |
            tcu-parser-macos.zip
          draft: false
          prerelease: false
          make_latest: true

      - name: Display release info
        run: |
          echo "========================================="
          echo "RELEASE PUBLISHED!"
          echo "========================================="
          echo ""
          echo "Release Tag: latest-macos"
          echo "Source Commit: ${{ steps.version.outputs.short_sha }}"
          echo "Build Date: ${{ steps.version.outputs.build_date }}"
          echo ""
          echo "Fixed download URL:"
          echo "https://github.com/thacio/markup_to_docx_parser_release/releases/download/latest-macos/tcu-parser-macos.zip"
          echo ""
          echo "View release:"
          echo "https://github.com/thacio/markup_to_docx_parser_release/releases/tag/latest-macos"
          echo ""
